final products = [
  {
    "id": "0",
    "title": "Men's Nike Shoe",
    "price": 44.52,
    "sizes": [8, 9, 10, 11],
    "company": "Nike",
    "imageUrl": "assets/images/shoes_1.png",
  },
  {
    "id": "1",
    "title": "Adidas Shoes",
    "price": 20.12,
    "sizes": [9, 10, 11],
    "company": "Adidas",
    "imageUrl": "assets/images/shoes_2.png",
  },
  {
    "id": "2",
    "title": "Jordan Shoes",
    "price": 420.69,
    "sizes": [8, 9, 10, 11],
    "company": "Nike",
    "imageUrl": "assets/images/shoes_4.png",
  },
  {
    "id": "3",
    "title": "Puma Men's Hybrid NX",
    "price": 58.30,
    "sizes": [7, 8, 9, 10, 11],
    "company": "Puma",
    "imageUrl": "assets/images/puma_hybrid_nx.png",
  },
  {
    "id": "4",
    "title": "Adidas Running Shoes",
    "price": 35.99,
    "sizes": [8, 9, 10],
    "company": "Adidas",
    "imageUrl": "assets/images/adidas_running.png",
  },
  {
    "id": "5",
    "title": "Nike Dunk High",
    "price": 110.00,
    "sizes": [9, 10, 11, 12],
    "company": "Nike",
    "imageUrl": "assets/images/nike_dunk_high.png",
  },
];
